### ISSUE TITLE
Docker Repo Creation Errors

### ISSUE THREAD

**Issue by drudnev** [wandenberg/puppet-module-nexus3_rest#7]
Getting errors when creating docker proxy repos
```
Error: Error while creating nexus3_repository docker-hub-proxy: Could not run the command due to '400' '{
  "name" : "b0a010e93737bd286ca1eb259a6cc936",
  "result" : "javax.script.ScriptException: javax.validation.ConstraintViolationException"
}'
```

```
2018-10-24 08:36:28,843-0700 INFO  [qtp391406810-8550]  admin org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl - Creating repository: docker-hub-proxy -> Configuration{repositoryName='docker-hub-proxy', recipeName='docker-proxy', attributes={proxy={remoteUrl=https://registry.hub.docker.com}, storage={strictContentTypeValidation=true, blobStoreName=default}, docker={httpPort=, v1Enabled=true, forceBasicAuth=true, httpsPort=}}}
2018-10-24 08:36:28,897-0700 WARN  [qtp391406810-8550]  admin org.sonatype.nexus.repository.config.internal.ConfigurationFacetImpl - Validation failed; 1 constraints violated:
  1) may not be null, type: class org.sonatype.nexus.repository.config.internal.ConfigurationFacetImpl$SectionWrapper, property: attributes[dockerProxy].indexType, value: null

2018-10-24 08:36:28,900-0700 ERROR [qtp391406810-8550]  admin org.sonatype.nexus.script.plugin.internal.rest.ScriptResource - Exception in script execution for script named: b0a010e93737bd286ca1eb259a6cc936
javax.script.ScriptException: javax.script.ScriptException: javax.validation.ConstraintViolationException
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:162)
	at org.sonatype.nexus.internal.script.ScriptServiceImpl.eval(ScriptServiceImpl.java:153)
	at org.sonatype.nexus.internal.script.ScriptServiceImpl.eval(ScriptServiceImpl.java:162)
	at org.sonatype.nexus.common.script.ScriptService$eval$1.call(Unknown Source)

```

**Comment by wandenberg** [comment]
Fix was merged
